agents:
  queue: "default-{queue}"

# retry:
#   automatic:
#       limit: 3

label: "{name} ({slug})"
key: "build-{slug}"

# commands:
#   - echo \"+++ Start Services\"
#   - bash scripts/tests/setup/start-services.sh
#   - echo \"+++ Build\"
#   - bash scripts/teamcity/10.build.sh
#   - echo \"+++ Test\"
#   - bash scripts/teamcity/20.test.sh
#   - echo \"+++ Examples\"
#   - bash scripts/teamcity/30.examples.sh
#   - echo \"+++ Documentation examples\"
#   - bash scripts/teamcity/40.documentation-examples.sh
#   - echo \"+++ Stop Services\"
#   - bash scripts/tests/setup/stop-services.sh

commands:
  - |
    export GOROOT="$$QDB_CICD_AGENT_GO125_ROOT"
    bash scripts/teamcity/10.build.sh

# plugins:
#   - bureau14/qdb-artifacts#master:
#       download:
#         project_id: "quasardb"
#         output-dir: "qdb"
#         extract: true
#         clean: true
#         files:
#           - "*-c-api.tar.zst!*"
#           - "*-server.tar.zst!*"
#           - "*-utils.tar.zst!*"
